version: '0.2'
language: en
allowCompoundWords: true
caseSensitive: false
ignoreRandomStrings: true
words:
  - bivariant
  - blueprintjs
  - Klass
  - noshiro
  - pikachu
  - sindresorhus
  - testw
  - tscw
  - TSES
  - tsutils
ignorePaths:
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - dist/**
  - docs/**
  - agents/common/**
  - test/**
